---

- name: sync game{{server_id}} files
  synchronize: 
    src: "{{local_path}}/" 
    dest: "{{ansible_env.HOME}}/game{{server_id}}"
    rsync_opts: 
      - "--exclude={{ignores | join(' --exclude=')}}" 
  tags:
    - deploy
    - update

- name: generate configuration
  template:
    src: config.properties.j2
    dest: "{{ansible_env.HOME}}/game{{server_id}}/config.properties"
  tags:
    - deploy
    - update

- name: start game{{server_id}}
  shell: ". /etc/profile && {{ansible_env.HOME}}/game{{server_id}}/run.sh -g start"
  args:
    chdir: "{{ansible_env.HOME}}/game{{server_id}}"
  async: 5
  poll: 1
  register: start_result
  tags: start

- name: start game{{server_id}} result
  debug: msg="{{lookup('file', start_result.results_file)}}"
  ignore_errors: yes
  tags: debug

- name: stop game{{server_id}}
  shell: "{{ansible_env.HOME}}/game{{server_id}}/run.sh -g stop"
  args:
    chdir: "{{ansible_env.HOME}}/game{{server_id}}"
  tags: stop

- name: verify game{{server_id}}
  stat: path="{{ansible_env.HOME}}/game{{server_id}}/EchoServer.class"
  register: st
  tags: verify

- name: verify result for game{{server_id}}
  debug: msg="{{st.stat.md5}}"
  tags: verify

- name: automatic verify
  #assert: { that: "st.stat.md5 == md5"}
  #when: md5 is defined
  fail: msg="game{{server_id}} md5 not match!"
  when: st.stat.md5 != md5
  tags: verify


