---

- name: sync game{{SERVER_ID}} files
  synchronize: 
    src: "{{local_path}}/" 
    dest: "{{ansible_env.HOME}}/game{{SERVER_ID}}"
    rsync_opts: 
      - "--exclude={{ignores | join(' --exclude=')}}" 
  tags:
    - deploy
    - update

- name: debug
  debug: msg="--exclude={{ignores | join(' --exclude=')}}"
  tags: debug

- name: generate configuration
  template:
    src: config.properties.j2
    dest: "{{ansible_env.HOME}}/game{{SERVER_ID}}/config.properties"
  tags:
    - deploy
    - update

- name: start game{{SERVER_ID}}
  shell: "source /etc/profile && {{ansible_env.HOME}}/game{{SERVER_ID}}/run.sh -g start"
  args:
    chdir: "{{ansible_env.HOME}}/game{{SERVER_ID}}"
  async: 5
  poll: 0
  tags: start

- name: stop game{{SERVER_ID}}
  shell: "{{ansible_env.HOME}}/game{{SERVER_ID}}/run.sh -g stop"
  args:
    chdir: "{{ansible_env.HOME}}/game{{SERVER_ID}}"
  tags: stop



