---
# 系统初始化

- name: install docker for {{ hosts }}
  hosts: '{{ hosts }}'
  vars:
    #version can be latest or stable
    version: 'latest'
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_os_family }}.yml"
    
  roles:
    - docker

