---
# ansible-playbook misc.yml --extra-vars "hosts=venus user=root"
- hosts: $hosts
  user: $user
  vars:
    isCentOS: "'${ansible_distribution}' == 'CentOS'"
    isDebian: "'${ansible_distribution}' == 'Debian'"
    isUbuntu: "'${ansible_distribution}' == 'Ubuntu'"
  vars_files: 
    - vars/${ansible_distribution}.yml

  tasks:

    # 增加网易开源镜像为更新源
    - include: playbooks/repository.yml

    # 确保git是最新版本
    - name: ensure git is at the latest version
      action: $packageManager pkg=git state=latest
      tags: git

    # 安装一些基础软件包
    - name: install basic packages
      action: $packageManager pkg=$item state=installed
      with_items: $basePackages
      tags: setup

    # zshell安装配置
    - name: ensure zsh is the latest
      action: $packageManager pkg=zsh state=latest
      tags: zsh
    - name: install oh-my-zsh
      action: shell chdir=~ creates=.zshrc curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh & /bin/true
      tags: zsh
    - name: check plugins in oh-my-zsh
      action: shell chdir=~ sed -n '/plugins=(git github pip virtualenvwrapper python ruby rails3)/p' .zshrc & /bin/true
      register: ohMyZshResult
      tags: zsh
    - name: enable plugins in oh-my-zsh
      action: shell chdir=~ sed -i 's/plugins=(git)/plugins=(git github pip virtualenvwrapper python ruby rails3)/' .zshrc
      only_if: "'${ohMyZshResult.stdout}'.find('plugins=') == -1"
      tags: zsh

    # vim安装配置
    - name: ensure vim is the latest
      action: $packageManager pkg=vim state=latest
      tags: vim
    - name: configure vim
      action: shell chdir=~ creates=.vim/vimrc curl -L https://github.com/jhezjkp/dot-vimrc/raw/master/tools/install.sh | sh
      tags: vim

    # python环境
    - include: playbooks/python.yml

    # ruby环境
    - include: playbooks/ruby.yml

    # java开发环境(安装包时会弹出窗口要求接受协议因而导致安装失败)
    #- name: ensure sun jdk6 is installed
    #  action: $packageManager pkg=sun-java6-jdk state=installed
    #  tags: java
