---
- hosts: debian
  user: root 
  tasks:
  - name: ensure git is at the latest version
    action: apt pkg=git state=latest
  - name: download easy_install
    action: command wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz#md5=7df2a529a074f613b509fb44feefe74e
  - name: exact easy_install
    action: command tar -zxvf setuptools-0.6c11.tar.gz
  - name: install easy_install
    action: command chdir=~/setuptools-0.6c11 python setup.py install
  - name: clean downloaded files
    action: command chdir=~ rm setuptools-0.6c11.tar.gz
  - name: ensure pip is installed
    action: easy_install name=pip
  - name: ensure virtualenv is installed
    action: easy_install name=virtualenv

