---
#该脚本用于上传公钥，命令：ansible-playbook RSA.yml --extra-vars "hosts=all user=root" -k
- hosts: $hosts
  user: $user
  tasks:
    - name: upload id rsa pub key
      action: authorized_key user=$user key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC54zsc1JqA3eozpRFO6rvukZZD2J+Dg4LDoErLcHYuE9kPUiiS27paQ63PKB/aIPj2dnBg6tF+/Itf5+W/63b4vGg0DYTGtOH/iltrObG9ZiZw8UTh6VF4Daf+ng/vbQib8vnbYE6nJoRjF28goSyXpGa5mzKnTM2iivitsR8nMw== viviastudio4secureCRT"
    # 如果是centos则需要下面的特别操作以确保在SELinux打开时也能用证书登录
    - name: special operation on centos
      action: shell /sbin/restorecon -Rv ~/.ssh
      only_if: "'${ansible_distribution}' == 'CentOS'"
