---
# 系统初始化

- name: setup ssh cert login and disable password login for {{ hosts }}
  hosts: '{{ hosts }}'
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_os_family }}.yml"
    
  roles:
    - ssh

