---
#设置公钥登录

- name: set public cert for user {{ansible_ssh_user}}
  authorized_key: user={{ansible_ssh_user}} key="{{ssh_pub_key}}"
  tags: ssh

- block:
  - name: change ssh port to {{ ssh_port }} 
    lineinfile: dest=/etc/ssh/sshd_config backup=yes regexp=^Port line='Port {{ ssh_port }}'
    notify:
      - restart ssh

  - name: change allow password login setting to {{ allow_password_auth}}
    lineinfile: dest=/etc/ssh/sshd_config backup=yes regexp=^PasswordAuthentication line='PasswordAuthentication {{ allow_password_auth }}'
    notify:
      - restart ssh
  become: yes
  #become_method: sudo


    
