---

- name: dowload shadowsocks-libev
  unarchive:
    src: https://github.com/shadowsocks/shadowsocks-libev/archive/master.zip
    copy: no
    dest: /tmp

- block:
  
  - name: install required softwares [debian/ubuntu]
    package: name={{item}}
    with_items:
      - make
      - gcc
      - zlib1g-dev
      - libssl-dev
      - daemon
    when: "{{ansible_os_family == 'Debian'}}"

  - name: install required softwares [rhel/centos]
    yum: name={{item}} state=present
    with_items:
      - make
      - gcc
      - zlib-devel
      - openssl-devel
    when: "{{ansible_os_family == 'RedHat'}}"

  - name: compile and install shadowsocks
    shell: ./configure && make && make install
    args:
      chdir: /tmp/shadowsocks-libev-master

  - name: create shadowsocks configure directory
    file: path=/etc/shadowsocks-libev state=directory

  - name: configure shadowsocks
    template:
      src: config.json.j2
      dest: /etc/shadowsocks-libev/config.json

  - name: get ss-server bin path
    shell: PATH=$PATH:/usr/local/bin && which ss-server
    register: ss_server_path

  - name: setup shadowsock service
    template:
      src: service.j2
      dest: "/etc/init.d/{{service_name}}"
      mode: 0744
      force: no
    vars:
      bin_path: "{{ss_server_path.stdout}}"
      bin_opts: ""

  - name: set shadowsock service start on boot and start it right now
    service: name={{service_name}} enabled=yes state=started
  
  become: yes
