---
#部署docker

- block:
  - name: install latest docker
    shell: curl -fsSL https://test.docker.com/ | sh
    when: version == 'latest'

  - name: install stable docker
    shell: curl -fsSL https://get.docker.com/ | sh
    when: version == 'stable'

  become: yes
  #become_method: sudo


    
